export default [
  {
    stockId: 1,
    symbol: "TSLA",
    price: "909.68",
    e_score: "3.0",
    s_score: "17.3",
    g_score: "10.2",
    total: "30",
    invest: false,
  }, {
    stockId: 2,
    symbol: "AMZN",
    price: "3,335.55",
    e_score: "6.7",
    s_score: "14.6",
    g_score: "9.7",
    total: "31",
    invest: false,
  }, {
    stockId: 3,
    symbol: "NFLX",
    price: "664.78",
    e_score: "0.1",
    s_score: "6.8",
    g_score: "9.9",
    total: "17",
    invest: true,
  }, {
    stockId: 4,
    symbol: "MSFT",
    price: "309.16",
    e_score: "0.5",
    s_score: "8.1",
    g_score: "4.7",
    total: "13",
    invest: true,
  }, {
    stockId: 5,
    symbol: "GOOGL",
    price: "2,751.33",
    e_score: "0.5",
    s_score: "10.8",
    g_score: "11.6",
    total: "23",
    invest: true,
  },
];
